; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = knolleary/PubSubClient@^2.8

[platformio]
default_envs = normal

[env:normal]

[env:provision]
build_flags =
    -D PROVISION_CONFIG
    -D OTA_DRY_RUN

[env:ota-dry-run]
build_flags =
    -D OTA_DRY_RUN
